# Script to compile the FPGA with zynq processor system all the way to bit file.
#report_timing_summary -file $outputDir/post_synth_timing_summary.rpt
#report_utilization -file $outputDir/post_synth_util.rpt
# this is to bypass error about muxed reference clock to MMCM.
# this tells the compiler about the configuration bank supply voltage.
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.PERSIST YES [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports cpu_reset]
set_property PACKAGE_PIN E1 [get_ports cpu_reset]

set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports pcie_perstn]
set_property PACKAGE_PIN A1 [get_ports pcie_perstn]

set_property PACKAGE_PIN F6 [get_ports pcie_refclk_P]
set_property PACKAGE_PIN E6 [get_ports pcie_refclk_N]


set_property PACKAGE_PIN B8 [get_ports {pcie_7x_mgt_rxp[3]}]
set_property PACKAGE_PIN B4 [get_ports {pcie_7x_mgt_txp[3]}]
set_property PACKAGE_PIN D11 [get_ports {pcie_7x_mgt_rxp[2]}]
set_property PACKAGE_PIN D5 [get_ports {pcie_7x_mgt_txp[2]}]
set_property PACKAGE_PIN B6 [get_ports {pcie_7x_mgt_txp[1]}]
set_property PACKAGE_PIN B10 [get_ports {pcie_7x_mgt_rxp[1]}]
set_property PACKAGE_PIN D7 [get_ports {pcie_7x_mgt_txp[0]}]
set_property PACKAGE_PIN D9 [get_ports {pcie_7x_mgt_rxp[0]}]


set_property PROHIBIT true [get_sites AA10]
set_property PROHIBIT true [get_sites AA11]
set_property PROHIBIT true [get_sites AA13]
set_property PROHIBIT true [get_sites AA14]
set_property PROHIBIT true [get_sites AA15]
set_property PROHIBIT true [get_sites AA16]
set_property PROHIBIT true [get_sites AA9]
set_property PROHIBIT true [get_sites AB10]
set_property PROHIBIT true [get_sites AB11]
set_property PROHIBIT true [get_sites AB12]
set_property PROHIBIT true [get_sites AB13]
set_property PROHIBIT true [get_sites AB15]
set_property PROHIBIT true [get_sites AB16]
set_property PROHIBIT true [get_sites AB17]
set_property PROHIBIT true [get_sites T14]
set_property PROHIBIT true [get_sites T15]
set_property PROHIBIT true [get_sites T16]
set_property PROHIBIT true [get_sites U15]
set_property PROHIBIT true [get_sites U16]
set_property PROHIBIT true [get_sites V10]
set_property PROHIBIT true [get_sites V13]
set_property PROHIBIT true [get_sites V14]
set_property PROHIBIT true [get_sites V15]
set_property PROHIBIT true [get_sites W10]
set_property PROHIBIT true [get_sites W11]
set_property PROHIBIT true [get_sites W12]
set_property PROHIBIT true [get_sites W14]
set_property PROHIBIT true [get_sites W15]
set_property PROHIBIT true [get_sites W16]
set_property PROHIBIT true [get_sites Y11]
set_property PROHIBIT true [get_sites Y12]
set_property PROHIBIT true [get_sites Y13]
set_property PROHIBIT true [get_sites Y14]
set_property PROHIBIT true [get_sites Y16]
set_property PROHIBIT true [get_sites Y17]

set_property PACKAGE_PIN W22 [get_ports {led[0]}]
set_property PACKAGE_PIN W21 [get_ports {led[1]}]
set_property PACKAGE_PIN AA21 [get_ports {led[2]}]
set_property PACKAGE_PIN AA20 [get_ports {led[3]}]
set_property PACKAGE_PIN Y22 [get_ports {led[4]}]
set_property PACKAGE_PIN AB21 [get_ports {led[7]}]
set_property PACKAGE_PIN AB22 [get_ports {led[6]}]
set_property PACKAGE_PIN Y21 [get_ports {led[5]}]
